### ISSUE TITLE
NLOHMANN_JSON_SERIALIZE_ENUM?

### ISSUE THREAD

**Issue by LYHSH** [bakercp/ofxSerializer#1]
NLOHMANN_JSON_SERIALIZE_ENUM   not define?

**Comment by bakercp** [comment]
Hi, you need to update your version of json.hpp to a more recent version (https://github.com/nlohmann/json/releases).  You can replace the `json.hpp` into your `openFrameworks/libs/json/include/json.hpp` with the new version.

**Comment by bakercp** [comment]
By the way, the json version will be updated in the next OF release and you won't need to update it manually.

**Comment by LYHSH** [comment]
Thank you!  I load a new version of  json.hpp and my project build sucess!
